export interface Article {
  slug: string;
  type: "Essay" | "Interview" | "Notebook" | "Letters";
  no: string;
  title: string;
  excerpt: string;
  author: string;
  readTime: string;
  date: string;
  image: string;
  body: string[];
}

export const articles: Article[] = [
  {
    slug: "in-defence-of-the-boring-first-draft",
    type: "Essay",
    no: "No. 014.01",
    title: "In Defence Of The Boring First Draft.",
    excerpt: "The first draft is allowed to be a failure of nerve. M. Reinhardt on why the writers she trusts begin every essay badly, and why she has come to suspect anyone who does not.",
    author: "Maya Reinhardt",
    readTime: "18 min",
    date: "14 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/261d27901adb56aacc9db5fd3d84815aa122fed6395a6952047801d03166feea.jpg",
    body: [
      "The blank page is not your enemy. Your enemy is the version of you that believes the first sentence must also be the best one.",
      "Every writer I have come to trust — and I mean trust in the way you trust a surgeon, which is to say with your life and your syntax — begins badly. They begin with the wrong word, the obvious word, the word that any competent undergraduate might reach for on a Tuesday afternoon when the library is quiet and nothing is at stake.",
      "This is not a failure. This is, in fact, the only honest way to begin.",
      "The boring first draft is not laziness dressed up in theory. It is a discipline. It requires you to resist the seduction of the arresting opening, the clever reversal, the sentence that announces its own intelligence before it has earned the right to do so. The boring draft says: I do not yet know what I am writing. Let me find out.",
      "I have been editing long enough to recognise the essay that has been written backwards — polished from the first sentence, controlled, contained, and entirely dead by the third paragraph. The writer was so concerned with impressing me at the door that they forgot to let anyone inside.",
      "The writers I return to — the ones whose work has changed how I read and therefore how I live — all have this quality of having thought on the page rather than before it. The essay feels discovered rather than constructed. This is an illusion, of course. It is the most carefully maintained illusion in prose. But you cannot maintain it if you begin by performing.",
      "Begin badly. Begin honestly. Begin with the sentence you are embarrassed to have written, and then, in the second draft, ask yourself why you are embarrassed. The answer is usually where the essay lives.",
    ],
  },
  {
    slug: "on-marginalia-with-an-archivist",
    type: "Interview",
    no: "No. 014.02",
    title: "On Marginalia, With An Archivist.",
    excerpt: "Anika Sato keeps a museum of other people's annotations. We asked her what they know that we don't.",
    author: "H. Okabe",
    readTime: "22 min",
    date: "12 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/3909e1490646aa938f96c7c6dedb2679ac35a5e40513d0a26e83b62e26933aa7.jpg",
    body: [
      "Anika Sato's office at the municipal archive is exactly what you would expect and nothing like it. There are books — thousands of them — but they are not arranged by subject or author or date. They are arranged, she explains, by the quality of their annotations.",
      "\"The best marginalia is always a little angry,\" she says, pulling down a copy of a 1962 collection of essays, its margins dense with a previous reader's fury. \"This one is exceptional. Whoever owned it disagreed with almost everything, and they were right about half of it.\"",
      "Sato has spent fifteen years collecting annotated books. She is particularly interested in the conversation that happens between a reader and a text — the moment when passive consumption becomes active argument.",
      "\"People think of reading as receiving,\" she says. \"But the best readers are always pushing back. The margin is where they push.\"",
      "We ask her what she has learned from the dead. She is quiet for a moment. Outside, a tram passes.",
      "\"That they were more uncertain than their published work suggests. Every annotation is a record of doubt. Even the angry ones — especially the angry ones — are people trying to make sense of something that resists them.\"",
      "She sets the book down carefully. \"I find that very comforting,\" she says.",
    ],
  },
  {
    slug: "a-week-of-single-sentence-days",
    type: "Notebook",
    no: "No. 014.03",
    title: "A Week Of Single-Sentence Days.",
    excerpt: "Seven days, seven sentences, one ill-advised experiment in radical restraint — with results.",
    author: "The Bureau",
    readTime: "6 min",
    date: "10 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/d3aa762bf76c97debeef5b829b765837af02967faa659fa325f59b2d5e2a0e44.jpg",
    body: [
      "Monday: The coffee is bad and the sentence about it is worse.",
      "Tuesday: Tried to describe the light through the window without using the word \"light\" — failed on the third attempt, succeeded on the seventh, and then could not decide if the seventh was better or simply more elaborate.",
      "Wednesday: One sentence about a phone call that lasted forty minutes: it was not enough and it was exactly right.",
      "Thursday: Wrote a sentence about writer's block that was itself blocked. Left it. Came back. Added a comma. Left it again.",
      "Friday: The sentence that arrived at eleven-fifteen in the morning, unbidden, about my grandmother's handwriting — this one I will keep. This one knows something I do not.",
      "Saturday: Rest. Even a sentence needs silence around it.",
      "Sunday: Seven days. Seven sentences. The experiment has taught me that I am slower than I thought and more patient than I feared. Next week: two sentences per day. We will see.",
    ],
  },
  {
    slug: "against-the-tidy-conclusion",
    type: "Essay",
    no: "No. 014.04",
    title: "Against The Tidy Conclusion.",
    excerpt: "Endings that pretend to resolve are, more often than not, hiding the actual argument three paragraphs back.",
    author: "P. Lindqvist",
    readTime: "14 min",
    date: "08 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/60112fffd04b3b534053952972d1161e4be3c8a2c1334bf3da7456d44fa68616.jpg",
    body: [
      "The tidy conclusion is a lie the essay tells itself. It gathers the loose threads, ties them with a bow, and presents the reader with a package that suggests: this is finished, this is resolved, you may now put it down.",
      "But the essay that resolves too cleanly has, in resolving, undone itself. The question was not answered — it was dismissed.",
      "I am not arguing for inconclusiveness as an aesthetic. The essay that trails off, shrugging, is no better than the one that snaps shut with false certainty. What I am arguing for is the ending that earns its incompleteness — that holds the tension it has built rather than releasing it into the comfortable.",
      "Montaigne, who invented this form and remains its most honest practitioner, almost never concludes. He accumulates. He adds. He circles back. His endings arrive not because the thought is finished but because the page is.",
      "This is, I think, the more truthful position. The thought is never finished. The essay is merely the length of one sitting, one sustained attention, before the world intervenes and you must put down the pen.",
      "The tidy conclusion pretends otherwise. It pretends that thought has a shape, that argument has a resolution, that the writer has arrived somewhere definitive. The honest ending admits that it is simply where you stopped.",
    ],
  },
  {
    slug: "dear-editor-march",
    type: "Letters",
    no: "No. 014.05",
    title: "Dear Editor — March.",
    excerpt: "On commas, the verb \"to leverage,\" and the reader from Bogotá who has caught us out.",
    author: "Readers",
    readTime: "9 min",
    date: "06 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/97e1cc4dad71ed9159bb413a874ca33d928e41101063c61ed67923361f517131.jpg",
    body: [
      "Dear Editor, — Your piece last month on the serial comma contained, in its third paragraph, a sentence that itself required one. I notice these things. I suspect you do too. — R.H., Edinburgh",
      "Dear Editor, — I have been a subscriber since the second issue. I have recommended you to eleven people. I mention this not to establish my credentials but to earn the right to say: please stop using the word \"leverage\" as a verb. It is not a verb. It has never been a verb. It is an affront to the memory of everyone who has ever held a lever. — C.M., Toronto",
      "Dear Editor, — In your February interview, the archivist says that the best annotations are \"always a little angry.\" I have been thinking about this for three weeks. I annotated the sentence itself, in the margin, with the word \"yes.\" I am not sure if this proves or disproves her point. — A.S., Bogotá",
      "Dear Editor, — I am writing to report that I read your notebook piece on single-sentence days to my writing group and we have now all attempted it. Results: two people found it liberating, three found it agonising, and one has not spoken to me since. I consider this a success. — T.O., Melbourne",
      "Dear Editor, — The essay on the boring first draft changed something for me. I have been writing badly with much greater confidence. Thank you. — Name withheld, Bristol",
    ],
  },
  {
    slug: "the-editor-as-reader-first",
    type: "Essay",
    no: "No. 014.06",
    title: "The Editor As Reader, First.",
    excerpt: "Why our best edits begin not in the manuscript but in the silence that follows the first read-through.",
    author: "Maya Reinhardt",
    readTime: "11 min",
    date: "04 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/8f0e6aedcc78c1c7d5c12574d2f75921ddf07cf2189cd7cdf6d434a3290999b5.jpg",
    body: [
      "The first thing I do when a new manuscript arrives is read it without a pen.",
      "This sounds obvious. It is not. Every editor I know — and I have known many, good and less good — reaches for the pencil on the second page. The instinct to correct is powerful, and in editing, it masquerades as professionalism.",
      "But the first read is not for correction. It is for experience. You are not yet an editor. You are a reader, encountering this thing for the first time, with all the vulnerability and goodwill that implies.",
      "The question you are trying to answer is not: what is wrong with this? The question is: what is this trying to be?",
      "These are different questions. The first produces a list of problems. The second produces an understanding. And you cannot fix what you do not understand.",
      "I put down the manuscript. I make tea. Sometimes I take a walk. I am thinking about the distance between what the essay is and what it is reaching for — that gap is where my work lives.",
      "Only then do I pick up the pen. And when I do, I am still trying to be, in some part of my attention, the reader I was before I became the editor.",
    ],
  },
  {
    slug: "the-paragraph-as-unit-of-thought",
    type: "Essay",
    no: "No. 014.07",
    title: "The Paragraph As Unit Of Thought.",
    excerpt: "We obsess over the sentence. We should be thinking in paragraphs — the true architecture of argument.",
    author: "P. Lindqvist",
    readTime: "13 min",
    date: "02 March 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/3909e1490646aa938f96c7c6dedb2679ac35a5e40513d0a26e83b62e26933aa7.jpg",
    body: [
      "Writing instruction is obsessed with the sentence. We teach sentence variety, sentence rhythm, sentence length. We speak of long sentences and short sentences as though they were the primary unit of prose.",
      "They are not. The paragraph is.",
      "The sentence is a stone. The paragraph is the wall. You can have beautiful stones and an ugly wall — most writers do. The arrangement is everything, and arrangement is the work of the paragraph.",
      "A paragraph has a job. It exists to move the reader from one position to another — intellectually, emotionally, argumentatively. The sentence within it is in service of that movement. A sentence that does not serve the paragraph's job has no business being there, however beautiful it might be in isolation.",
      "This is the hardest thing to teach and the most important thing to learn: the willingness to cut the beautiful sentence that serves only itself.",
      "The paragraph says: this is one thought, fully thought. The space between paragraphs says: I am now thinking something adjacent, something in tension, something that follows. This rhythm — of accumulation and pause — is the fundamental rhythm of essayistic prose.",
      "Learn your sentences. But think in paragraphs.",
    ],
  },
  {
    slug: "on-revision-with-a-poet",
    type: "Interview",
    no: "No. 014.08",
    title: "On Revision, With A Poet.",
    excerpt: "Kwame Asante has written the same poem forty-three times. We asked him when it becomes something new.",
    author: "H. Okabe",
    readTime: "17 min",
    date: "28 February 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/d3aa762bf76c97debeef5b829b765837af02967faa659fa325f59b2d5e2a0e44.jpg",
    body: [
      "Kwame Asante has forty-three drafts of the same poem in a manila folder on his desk. He shows me draft one — seventeen lines, typed on a manual typewriter, three words crossed out in blue ink — and draft forty-three: nine lines, handwritten, two words circled as though still under review.",
      "\"They are the same poem,\" he says, \"in the way that a river is the same river.\"",
      "We ask him at what point revision becomes a new poem. He looks at the folder for a long time.",
      "\"When the original impulse is gone and something else has replaced it. But the impulse is never quite gone. It's more like — the poem remembers what it wanted to be, even when I've taken it somewhere else entirely.\"",
      "He has published fourteen collections. He shows me the folder the way some people show photographs of their children — with pride and anxiety in equal measure.",
      "\"The forty-third draft is not better than the first,\" he says carefully. \"It is more honest. The first draft knew something the forty-third has had to argue its way back to.\"",
      "We ask which version he would publish. He laughs. \"The forty-fourth,\" he says.",
    ],
  },
  {
    slug: "dear-editor-april",
    type: "Letters",
    no: "No. 014.09",
    title: "Dear Editor — April.",
    excerpt: "On white space, the semicolon, and the subscriber who has been reading us upside down since 2023.",
    author: "Readers",
    readTime: "8 min",
    date: "26 February 2025",
    image: "https://cdn.wonder.so/images/019e78d3-8c57-7249-90b5-12594e7963ad/97e1cc4dad71ed9159bb413a874ca33d928e41101063c61ed67923361f517131.jpg",
    body: [
      "Dear Editor, — I have been reading your journal upside down since the third issue. Not metaphorically. I find that text, when inverted, reveals the quality of its white space — the breathing room the editor has or has not allowed between thoughts. Yours is, I am pleased to report, generally well-aired. — F.K., Reykjavík",
      "Dear Editor, — A note on your recent semicolons: you are using them correctly, which is rarer than it should be, and I wanted to say so. Most publications now treat the semicolon as an em dash with pretensions. You do not. Thank you. — M.V., Vienna",
      "Dear Editor, — The interview with the archivist last month prompted me to go back through my own annotated books. I found, in the margin of a novel I read at twenty-two, the words \"this is wrong but I cannot say why.\" I am forty-seven now. I still cannot say why. — G.O., Lagos",
      "Dear Editor, — Your piece on the boring first draft has resulted in my writing group producing, collectively, forty-eight pages of deliberately terrible prose. We are very proud. — S.L., Amsterdam",
      "Dear Editor, — I read you on the train, always. I wanted you to know that your journal is the only thing that makes the 6:42 from Paddington feel, briefly, like a choice. — Name withheld, London",
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
